; إعدادات PlatformIO لجهاز ESP32
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.1.0
    links2004/WebSockets@^2.6.1
build_flags =
    -DDEVICE_ID=\"esp32-001\"
    -DDEVICE_TOKEN=\"c5b7bedbe3015d44b9203858f2623681f83fafb08a661748\"
    -DSERVER_HOST=\"172.20.10.2\"
    -DSERVER_PORT=3000
    -DUSE_TLS=0
